name = "My Awesome Project"

[viewport]
clear_color = [0.1, 0.1, 0.1, 1.0]

[[shader]]
name = "Shader"
type = "glsl"
vertex_shader = "assets/vs.glsl"
fragment_shader = "assets/frag.glsl"

[camera]
position = [-3.0, 2.0, 20.0]
fov = 70

[[model]]
path = "assets/models/teapot.obj"

[render_pipeline]
name = "my_pipeline"
shader_name = "Shader"

[[render_pipeline.bind_group]]
index = 0
type = "camera"

[[render_pipeline.bind_group]]
index = 1
type = "time"
