use winit::event_loop::EventLoop;

use crate::{
    app::App,
    error::AppResult,
    file::identifier::{ProjectIdentifier, ProjectSource},
    ui::components::create_project_modal::ProjectCreationSource,
    utils::winit_runner,
};

macro_rules! toasts_log_error {
    ($toasts:expr, $format:expr) => {
        let error = format!($format);
        log::error!("{error}");
        $toasts.error(error);
    };
}

/// Build-time metadata generated by the `built` crate in `build.rs`
pub mod built_info {
    include!(concat!(env!("OUT_DIR"), "/built.rs"));
}

mod app;
mod error;
mod file;
mod main_menu;
mod project;
mod scene;
pub mod startup;
mod ui;
mod utils;
mod workspace;

#[derive(Default)]
pub enum StartupAction {
    #[default]
    MainMenu,
    OpenProject {
        project_id: ProjectIdentifier,
    },
    CreateProject {
        source: ProjectSource,
        creation: ProjectCreationSource,
    },
}

pub fn run(startup_action: StartupAction) -> AppResult<()> {
    let event_loop = EventLoop::<App>::with_user_event().build()?;

    #[allow(unused_mut)]
    let mut attributes = winit::window::Window::default_attributes().with_title("Rau");

    #[cfg(not(target_arch = "wasm32"))]
    {
        use winit::dpi::LogicalSize;

        attributes = attributes.with_inner_size(LogicalSize::new(1280, 800));
        attributes = crate::utils::icon::apply_icon(attributes);
    }

    #[cfg(not(target_arch = "wasm32"))]
    {
        let mut app = winit_runner::WinitRunner::new(startup_action, attributes);
        event_loop.run_app(&mut app)?;
    }
    #[cfg(target_arch = "wasm32")]
    {
        use winit::platform::web::EventLoopExtWebSys;

        let app = winit_runner::WinitRunner::new(&event_loop, startup_action, attributes);
        event_loop.spawn_app(app)
    }

    Ok(())
}

#[cfg(target_arch = "wasm32")]
#[wasm_bindgen::prelude::wasm_bindgen(start)]
pub fn run_web() -> Result<(), wasm_bindgen::JsValue> {
    use wasm_bindgen::UnwrapThrowExt;

    console_error_panic_hook::set_once();
    console_log::init_with_level(log::Level::Info).unwrap_throw();

    run(startup::url::startup_action_from_url()).unwrap_throw();

    Ok(())
}
