use crate::{
    app::{App, AppSettings},
    file::{
        file_system::AppFileSystem,
        identifier::{ProjectIdentifier, ProjectSource},
    },
    ui::components::create_project_modal::ProjectCreationSource,
    utils::render_settings::RenderSettings,
};

macro_rules! toasts_log_error {
    ($toasts:expr, $format:expr) => {
        let error = format!($format);
        log::error!("{error}");
        $toasts.error(error);
    };
}

/// Build-time metadata generated by the `built` crate in `build.rs`
pub mod built_info {
    include!(concat!(env!("OUT_DIR"), "/built.rs"));
}

mod app;
mod error;
mod file;
mod main_menu;
mod project;
#[cfg(not(target_arch = "wasm32"))]
mod scene;
pub mod startup;
mod ui;
mod utils;
mod workspace;

#[derive(Default)]
pub enum StartupAction {
    #[default]
    MainMenu,
    OpenProject {
        project_id: ProjectIdentifier,
    },
    CreateProject {
        source: ProjectSource,
        creation: ProjectCreationSource,
    },
}

pub struct StartupSettings {
    pub app: AppSettings,
    pub render_settings: RenderSettings,
    #[cfg(not(target_arch = "wasm32"))]
    pub window_settings: startup::cli::WindowSettings,
}

#[cfg(not(target_arch = "wasm32"))]
pub fn run(settings: StartupSettings) -> error::AppResult<()> {
    use pollster::FutureExt as _;

    let app_file_system = AppFileSystem::open().block_on()?;

    let window_settings = &settings.window_settings;

    eframe::run_native(
        "Rau",
        eframe::NativeOptions {
            viewport: egui::ViewportBuilder::default()
                .with_title("Rau")
                .with_inner_size([window_settings.width as f32, window_settings.height as f32])
                .with_icon(crate::utils::icon::load_icon()),
            wgpu_options: app::wgpu_options(&settings.render_settings),
            ..Default::default()
        },
        Box::new(move |cc| {
            let app = App::new(cc, settings.app, app_file_system);
            Ok(Box::new(app.map_err(|error| error.to_string())?))
        }),
    )?;

    Ok(())
}

#[cfg(target_arch = "wasm32")]
#[wasm_bindgen::prelude::wasm_bindgen(start)]
pub fn run_web() -> Result<(), wasm_bindgen::JsValue> {
    use wasm_bindgen::{JsCast, UnwrapThrowExt};

    console_error_panic_hook::set_once();
    console_log::init_with_level(log::Level::Info).unwrap_throw();

    let canvas: web_sys::HtmlCanvasElement = web_sys::window()
        .unwrap_throw()
        .document()
        .unwrap_throw()
        .get_element_by_id("canvas")
        .expect_throw("canvas element not found")
        .dyn_into()
        .expect_throw("element is not a canvas");

    let StartupSettings {
        app: app_settings,
        render_settings,
    } = startup::url::startup_settings_from_url();

    wasm_bindgen_futures::spawn_local(async move {
        let app_file_system = AppFileSystem::open()
            .await
            .expect_throw("Failed to open the file system");

        eframe::WebRunner::new()
            .start(
                canvas,
                eframe::WebOptions {
                    wgpu_options: app::wgpu_options(&render_settings),
                    ..Default::default()
                },
                Box::new(move |cc| {
                    let app = App::new(cc, app_settings, app_file_system);
                    Ok(Box::new(app.map_err(|error| error.to_string())?))
                }),
            )
            .await
            .expect_throw("Failed to start eframe");
    });

    Ok(())
}
