# Based on https://github.com/matthewjberger/wgpu-example/blob/main/.github/workflows/pages.yml

name: Publish Page

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1
      - name: Download and install Trunk binary
        uses: jetli/trunk-action@v0.5.0
        with:
          version: 'latest'
      - name: Build
        run: trunk build --release --features "wgpu/webgl"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4